frontend/src/main/java/DishController.java
import se.josoder.exam.backend.ejb.DishEjb;
import se.josoder.exam.backend.entity.Dish;

import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;
import java.io.Serializable;
import java.util.List;

/**
 * Created by josoder on 07.06.17.
 */
@Named
@SessionScoped
public class DishController implements Serializable{
    @EJB
    private DishEjb dishEjb;
    @Inject
    private LoginController loginController;

    private String formName;
    private String formDescription;

    public List<Dish> getAllDishes(){
        return dishEjb.getAllDishes();
    }

    public void addDish(){
        if(!loginController.isLoggedIn()){
            return;
        }
        try {
            dishEjb.createDish(formName, formDescription);
        } catch (Exception e){
        }
    }

    public String getFormName() {
        return formName;
    }

    public void setFormName(String formName) {
        this.formName = formName;
    }

    public String getFormDescription() {
        return formDescription;
    }

    public void setFormDescription(String formDescription) {
        this.formDescription = formDescription;
    }
}

frontend/src/main/java/LoginController.java
import se.josoder.exam.backend.ejb.UserEjb;

import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;
import java.io.Serializable;

/**
 * Created by josoder on 08.06.17.
 */
@Named
@SessionScoped
public class LoginController implements Serializable {
    @EJB
    private UserEjb userEjb;

    private String formUsername;
    private String formPassword;
    private String formConfirmPassword;
    private String formFirstName;
    private String formLastname;

    private String loggedOnUser;

    public String createUser(){
        if(!formConfirmPassword.equals(formPassword)){
            return "createUser.jsf";
        }

        boolean valid=false;

        try {
            valid = userEjb.createUser(formUsername, formFirstName, formLastname, formPassword);
        } catch (EJBException e){
            // e.printStackTrace();
        }
        if(!valid){
            return "createUser.jsf";
        }
        return "home.jsf";
    }

    public boolean isLoggedIn(){
        return loggedOnUser!=null;
    }

    public String login(){
        if (userEjb.userLogin(formUsername, formPassword)){
            loggedOnUser = formUsername;
            return "home.jsf";
        } else
        return "login.jsf";
    }

    public String logOut(){
        loggedOnUser = null;
        return "home.jsf";
    }

    public String getFormUsername() {
        return formUsername;
    }

    public void setFormUsername(String formUsername) {
        this.formUsername = formUsername;
    }

    public String getFormPassword() {
        return formPassword;
    }

    public void setFormPassword(String formPassword) {
        this.formPassword = formPassword;
    }

    public String getFormConfirmPassword() {
        return formConfirmPassword;
    }

    public void setFormConfirmPassword(String formConfirmPassword) {
        this.formConfirmPassword = formConfirmPassword;
    }

    public String getFormFirstName() {
        return formFirstName;
    }

    public void setFormFirstName(String formFirstName) {
        this.formFirstName = formFirstName;
    }

    public String getFormLastname() {
        return formLastname;
    }

    public void setFormLastname(String formLastname) {
        this.formLastname = formLastname;
    }

    public String getLoggedOnUser() {
        return loggedOnUser;
    }

    public void setLoggedOnUser(String loggedOnUser) {
        this.loggedOnUser = loggedOnUser;
    }
}

frontend/src/main/java/MenuController.java
import se.josoder.exam.backend.ejb.DishEjb;
import se.josoder.exam.backend.ejb.MenuEjb;
import se.josoder.exam.backend.entity.Dish;
import se.josoder.exam.backend.entity.Menu;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;
import java.io.Serializable;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.stream.Collectors;

/**
 * Created by josoder on 07.06.17.
 */
@Named
@SessionScoped
public class MenuController implements Serializable {
    public static final int DEFAULT = 0;
    public static final int NEXT = 1;
    public static final int PREVIOUS = -1;
    @EJB
    private MenuEjb menuEjb;
    @Inject
    private DishEjb dishEjb;
    @Inject
    private LoginController loginController;

    private Map<String, Boolean> menuDishMap;
    private String formDate;
    private int menuChoice = 0;
    private Menu currentMenu = new Menu();


    public String addMenu(){
        if(!loginController.isLoggedIn()){
            return "home.jsf";
        }
        HashSet<Dish> dishes = getDishes();
        System.out.println(dishes.size());
        if(formDate==null||formDate.isEmpty()){
            return "menus.jsf";
        }
        if(dishes.size()==0){
            return "menus.jsf";
        }

        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDate date = LocalDate.parse(formDate, dtf);

        Long m = null;
        try {
            m = menuEjb.createMenu(date, dishes);
        } catch (Exception e){
            e.printStackTrace();
        }

        if(m==null){
            return "menus.jsf";
        } else {
            return "home.jsf";
        }
    }

    public List<Dish> getAllDishes(){
        List<Dish> dishes = dishEjb.getAllDishes();
        menuDishMap = new HashMap<>();

        dishes.stream().forEach(d ->
            menuDishMap.put(d.getName(), false));

        return dishes;
    }

    private HashSet<Dish> getDishes(){
        return menuDishMap.entrySet().stream()
                .filter(m -> m.getValue()==true)
                .map(m -> dishEjb.getDish(m.getKey()))
                .collect(Collectors.toCollection(HashSet::new));
    }

    public void onClick(String name, boolean value){
        menuDishMap.put(name, value);
    }

    public String getFormDate() {
        return formDate;
    }

    public void setFormDate(String formDate) {
        this.formDate = formDate;
    }

    public Map<String, Boolean> getMenuDishMap() {
        return menuDishMap;
    }

    public void setMenuDishMap(Map<String, Boolean> menuDishMap) {
        this.menuDishMap = menuDishMap;
    }


    // on click
    public String editMenuChoice(int id){
        if(!loginController.isLoggedIn()){
            return "home.jsf";
        }
        this.menuChoice = id;
        setCurrent();
        return "home.jsf";
    }

    private void setCurrent(){
        if(menuChoice==PREVIOUS && hasPrevious()){
            currentMenu = getPrevious();
        } else if(menuChoice==DEFAULT){
            currentMenu = menuEjb.getMenuForDate(LocalDate.now());
        } else if(menuChoice==NEXT&&hasNext()){
            currentMenu = getNext();
        }
    }

    public Menu getCurrentMenu(){
        if(currentMenu.getDate() == null) setCurrent();
        return currentMenu;
    }

    public Menu getNext(){
        return menuEjb.getFutureMenu(currentMenu.getDate());
    }

    public boolean hasNext(){
        if(menuEjb.getFutureMenu(currentMenu.getDate())!=null){
            return true;
        }
        return false;
    }

    public Menu getPrevious(){
        return menuEjb.getPastMenu(currentMenu.getDate());
    }

    public boolean hasPrevious(){
        if(menuEjb.getPastMenu(currentMenu.getDate())!=null){
            return true;
        }
        return false;
    }

    public boolean hasMenus(){
        if(menuEjb.getMenuForDate(LocalDate.now())==null){
            return false;
        }
        else return true;
    }
}

frontend/src/main/webapp/createUser.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
<ui:composition template="layout.xhtml">
    <ui:define name="title">Register User</ui:define>
    <ui:define name="content">
        <h:form id = "registerForm">
        <h:panelGrid columns="2">
            <h:outputText value="Username: "/>
            <h:inputText id = "userName" value="#{loginController.formUsername}"/>

            <h:outputText value="First name: " />
            <h:inputText id ="firstName" value="#{loginController.formFirstName}"/>

            <h:outputText value="Last name: " />
            <h:inputText id="lastName" value="#{loginController.formLastname}"/>

            <h:outputText value="Password: "/>
            <h:inputSecret id="password" value="#{loginController.formPassword}"/>

            <h:outputText value="Confirm password: "/>
            <h:inputSecret id="confirmPassword" value="#{loginController.formConfirmPassword}"/>

            <h:commandButton value="Register" id="regUserBtn" action="#{loginController.createUser}"/>
        </h:panelGrid>
        </h:form>
    </ui:define>
</ui:composition>
</html>

frontend/src/main/webapp/dishes.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
>
<ui:composition template="layout.xhtml">
    <ui:define name="title">MyCantina Dishes</ui:define>
    <ui:define name="content">
        <c:if test="#{loginController.loggedIn}">
        <h:form id = "createDishForm">
            <h:panelGrid columns="2">
                <h:outputText value="Name of dish: "/>
                <h:inputText value="#{dishController.formName}" id = "dishName"/>
                <h:outputText value="Description: " />
                <h:inputText value="#{dishController.formDescription}" id = "dishDescription"/>
            </h:panelGrid>
            <h:commandButton value="Create" id = "createBtn" action="#{dishController.addDish}"/>
        </h:form>


    <c:set var = "dishList" value="#{dishController.allDishes}"/>
    <c:choose>
        <c:when test="#{dishList.size() == 0}">
            <h:outputText value="No dishes to display yet =/"/>
        </c:when>
        <c:otherwise>
            <h:dataTable value="#{dishList}" var="dish" border="1" id="dishTable">
                <h:column>
                    <f:facet name="header">Name</f:facet>
                    <h:outputText value="#{dish.name}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">Description</f:facet>
                    <h:outputText value="#{dish.description}"/>
                </h:column>
            </h:dataTable>
        </c:otherwise>
    </c:choose>
        </c:if>
    </ui:define>
</ui:composition>
</html>

frontend/src/main/webapp/home.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0-SNAPSHOT Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">

<ui:composition template="layout.xhtml">
    <ui:define name="title">MyCantina Home Page</ui:define>
    <ui:define name="content">
        <c:if test="#{loginController.loggedIn}">
        <h:link value="Link to Dishes" outcome="dishes.jsf" id="dishesLink"/>
        <br/>
        <h:link value="Link to Menu" outcome="menus.jsf" id="menusLink"/>
        <hr/>
        </c:if>
        <c:choose>
            <c:when test="#{!menuController.hasMenus()}">
                <h:outputText value="No menus avaialable =/"/>
            </c:when>
            <c:otherwise>
                <h:form id = "changeDateForm">
                <h:commandLink id="showDefault" value="Show default" action="#{menuController.editMenuChoice(0)}"/>

                <br/>
                <c:if test="#{menuController.hasNext()}">
                    <h:commandLink id = "showNext" value="Show next #{menuController.next.date.toString()}"
                                   action="#{menuController.editMenuChoice(1)}"/>
                    <br/>
                </c:if>

                    <c:if test="#{menuController.hasPrevious()}">
                        <h:commandLink id = "showPrevious" value="Show previous #{menuController.previous.date.toString()}" action="#{menuController.editMenuChoice(-1)}"/>
                    </c:if>

                <c:set value="#{menuController.currentMenu}" var="current"/>

                <h2>
                    <h:outputText value="Menu for #{current.date.toString()}" id = "menuDate"/>
                </h2>

                <h:dataTable var="dish" id="menuTable" value="#{current.dishes}" border="1">
                    <h:column>
                        <f:facet name="header">Name</f:facet>
                        <h:outputText id="dishName" value="#{dish.name}"/>
                    </h:column>
                    <h:column>
                        <f:facet name="header">Description</f:facet>
                        <h:outputText id="dishDescription" value="#{dish.description}"/>
                    </h:column>
                </h:dataTable>
                </h:form>
            </c:otherwise>
        </c:choose>
    </ui:define>
</ui:composition>
</html>

frontend/src/main/webapp/layout.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
<h:head>
    <title>
        <ui:insert name="title">Defualt title</ui:insert>
    </title>
</h:head>

<h:body>
    <h:outputText value="MyCantina Application"/>
    <hr/>
    <h:link value="Home" outcome="home.jsf"/>

    <h1>
        <ui:insert name="title">Default title</ui:insert>
    </h1>
    <c:choose>
        <c:when test="#{loginController.loggedIn}">
            <h:outputText id = "signedInUser" value="Signed in as #{loginController.loggedOnUser}"/>
            <h:form id = "logOutForm">
            <h:commandButton id = "logOut" value="Log out" action="#{loginController.logOut}"/>
            </h:form>
        </c:when>
        <c:otherwise>
            <h:outputText id = "notLoggedIn" value="You are not signed in, login or register to get chef-access"/>
            <br/>
            <h:link id="loginLink" value="login" outcome="login.jsf"/>
            <br/>
            <h:link id="createUserLink" value="register" outcome="createUser.jsf"/>
        </c:otherwise>
    </c:choose>

    <hr/>
    <ui:insert name="content">
    </ui:insert>
</h:body>
</html>

frontend/src/main/webapp/login.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<ui:composition template="layout.xhtml">
    <ui:define name="title">Login page</ui:define>
    <ui:define name="content">
        <h:form id = "loginForm">
            <h:column>
                <h:outputText value="Username:"/>
                <h:inputText id = "username" value="#{loginController.formUsername}"/>
            </h:column>
            <br/>
            <h:column>
                <h:outputText value="Password:"/>
                <h:inputSecret id="password" value="#{loginController.formPassword}"/>
            </h:column>
            <h:commandButton value="Sign in" id="signInBtn" action="#{loginController.login()}"/>
        </h:form>
    </ui:define>

</ui:composition>
</html>

frontend/src/main/webapp/menus.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
>
<ui:composition template="layout.xhtml">
    <ui:define name="title">MyCantina Menus</ui:define>
    <ui:define name="content">
        <c:if test="#{loginController.loggedIn}">
        <h:form id="createMenu">
            <h:outputText value="Date:"/>
            <h:inputText value="#{menuController.formDate}" id = "date"/>
            <h:commandButton id = "createBtn" value="create" action="#{menuController.addMenu}"/>


            <c:set var="dishList" value="#{menuController.allDishes}"/>

            <c:choose>
                <c:when test="#{dishList.size()== 0}">
                    <br/>
                    <h:outputText value="you need to create dishes first"/>
                </c:when>
                <c:otherwise>
                    <h:dataTable value="#{dishList}" var="dish" border="1" id="menuDishTable">
                        <h:column>
                            <f:facet name="header">Name</f:facet>
                            <h:outputText value="#{dish.name}" id = "dishName"/>
                        </h:column>

                        <h:column>
                            <f:facet name="header">Include?</f:facet>
                            <h:selectBooleanCheckbox id="includeCheck"
                                                     value="#{menuController.menuDishMap[dish.name]}"/>
                        </h:column>
                    </h:dataTable>
                </c:otherwise>
            </c:choose>
        </h:form>
        </c:if>
    </ui:define>
</ui:composition>
</html>